---
title: "연구과제"
---

## 수행 중

| 기간 | 연구과제명 | 지원기관 | 수행기관 | 역할 |
|---|---|---|---|---|
| 2026.04-2026.12 | 제2차 기후보건영향평가 기획 및 수행 | 질병관리청 | 대한예방의학회 | 참여연구원 |
| 2026.04-2026.12 | 기후보건 실태조사 및 인식도 조사 기획·수행 | 질병관리청 | 연세대학교 산학협력단 | 참여연구원 |

## 종료

| 기간 | 연구과제명 | 지원기관 | 수행기관 | 역할 |
|---|---|---|---|---|
| 2026.03-2026.07 | 경남RISE-의과대학 교육혁신 지원사업: 암검진 지역 격차 분석을 활용한 지역의료 문제 해결형 의학교육 콘텐츠 개발 | 경상국립대학교 의과대학 | 경상국립대학교 의과대학 의학과 예방의학교실 | 책임연구원 |
| 2025.03-2025.12 | 제2차 기후보건영향평가 지표 개발, 평가체계 정립 및 정책 활용방안 연구 | 질병관리청 | 대한예방의학회 | 참여연구원 |
| 2023.03-2023.12 | 기후보건 정보이해력 제고 방안 연구 | 질병관리청 | 경상국립대학교 산학협력단 | 책임연구원 |
| 2023.03-2023.12 | 기후변화 관련 극한기후의 건강영향 연구 | 질병관리청 | 한양대학교 산학협력단 | 참여연구원 |
| 2022.05-2022.12 | 기후변화에 따른 노령인구의 건강영향평가 연구 | 질병관리청 | 아주대학교 산학협력단 | 참여연구원 |
| 2022.05-2022.12 | 제3기(‘18~’22) 국가산단 지역 주민 환경오염노출 및 건강영향조사 –종합평가- | 국립환경과학원 | 단국대학교 산학협력단 | 참여연구원 |
| 2022.04-2022.12 | 제1차 기후보건영향평가 결과 대국민 소통 콘텐츠 개발 | 질병관리청 | 대한예방의학회 | 참여연구원 |
| 2021.04-2024.12 | 민감·취약계층 개인 맞춤형 환경보건 서비스 개발을 위한 리빙랩 구축 | 한국환경산업기술원 | 연세대학교 산학협력단 | 참여연구원 |
| 2021.04-2021.12 | 기후보건영향평가 수립에 관한 연구 | 질병관리청 | 경상국립대학교 산학협력단 | 참여연구원 |
| 2021.04-2021.12 | 진드기 매개 감염병 예방관리사업 | 질병관리청 | 대한예방의학회 | 참여연구원 |
| 2021.03-2024.02 | 경남 서부 10개 보건소 지역사회건강조사 | 질병관리청 | 경상국립대학교 산학협력단 | 참여연구원 |
| 2021.03-2021.10 | 미세먼지 건강보호 온라인 교육 개발 | 질병관리청 | 경상국립대학교 산학협력단 | 참여연구원 |
| 2021.02-2021.12 | 지역 내 소지역 건강격차 해소 사업 | 남해군 | 연세대학교 원주산학협력단 | 참여연구원 |

---