---
title: "논문"
---

## 2026

48. **Engagement in Particulate Matter Exposure Reduction Behaviors Across Diverse Clinical Cohorts**\
Sung Woo Moon, Ji Ye Jung, Hyun Woo Ji, Dae-Ryong Kang, Yong Jin Lee, Jin-Bae Kim, Yeong-Bae Lee, Changsoo Kim, Jaelim Cho, Mi-Ji Kim, Hye Jin Park, Young Sam Kim\
Medicina

49. **Impact of heat on respiratory health: Age-and sex-specific risks in a nationwide Korean study (2014–2019)**\
Joonho Ahn, Jongmin Oh, Ho-Jang Kwon, Hyungryul Lim, Jonghyuk Choi, Sanghyuk Bae, Kyoung-Nam Kim, Mi-Ji Kim, Jong-Hun Kim, Youn-Hee Lim\
International Journal of Biometeorology

50. **High prevalence of non-receipt of cancer-directed therapy among the oldest old persists independent of healthcare accessibility: A population-based analysis of 82,864 patients**\
Se-Il Go, Rock Bum Kim, Mi-Ji Kim, Ki-Soo Park, Byeong Sun Moon, Woo Je Lee, Jung Hun Kang\
Cancer Epidemiology (online)

51. **Determinants of Out-of-Region Healthcare Use and Patient Experiences in Brain Disorders in Gyeongsangnam-Do : An Andersen’s Behavioral Model Approach**\
KO Go, K Hwang, JH Han, CY Kim, SH Seo, MJ Kim, JH Sung\
Journal of Korean Neurosurgical Society (online)

## 2025

43. **Hemicentral Retinal Vein Occlusion: Clinical Outcomes and Visual Prognostic Factors**\
Dong Woo Lee, Do Yun Song, Mi-Ji Kim, Yong Wun Cho, Woong-Sun Yoo, In Young Chung\
Journal of Korean Ophthalmological Society

44. <span style="color:blue;">**Factors Affecting Subjective Well-Being in Workers at Small-Sized Enterprises: A Cross-Sectional Study from the 6th Korean Working Conditions Survey**</span>\
SangJin Park, Mi-Ji Kim, Joo Hyun Sung\
Yonsei Medical Journal

45. <span style="color:blue;">**Factors Associated with the Utilization of Out-of-Region Medical Institutions for Brain Diseases**</span>\
Kyeong-O Go, Mi-Ji Kim, Kihwan Hwang, Seong-Hyo Seo, Joo Hyun Sung\
Yonsei Medical Journal

46. <span style="color:blue;">**Factors Influencing Indoor Xylene Concentrations and Biomarkers in the General Population Based on the 2020–2021 KNHANES**</span>\
Mi-Ji Kim, SangJin Park, Ahra Kim, Joo Hyun Sung\
Yonsei Medical Journal

47. **Associations Between Urinary Metabolites of Polycyclic Aromatic Hydrocarbons and Liver Enzyme Levels Among Korean Firefighters**\
Jaeyong Lee, Mun-Joo Bae, Mi-Ji Kim, Sung Soo Oh, Ki Soo Park, Chan Joo Lee, Sungha Park, Seung-Koo Lee, Sang-Baek Koh, Hyeon Chang Kim, Changsoo Kim, Jaelim Cho\
Journal of Preventive Medicine and Public Health

## 2024

40. <span style="color:blue;">**Occupational hazardous factors and health impacts among agricultural workers: A Mechanism-Based review**</span>\
Mi-Ji Kim, Ki-Soo Park, SangJin Park, Hansoo Song, Seok-Ju Yoo, Won-Ju Park, Seong-yong Yoon, Dong-phil Choi, Joo Hyun Sung\
Journal of agricultural medicine and community health

41. **Personality and Learning Behavioral Characteristics as Predictors of Academic Achievement of Medical Students**\
Jang-Rak Kim, Young-A Ji, Mi-Ji Kim, Jong Ryeal Hahm\
Korean Medical Education Review

42. **Polycyclic Aromatic Hydrocarbons Mediate the Association between Tobacco Smoking and Alcohol Use Disorder**\
Dongkyu Lee, Mun-Joo Bae, Mi-Ji Kim, Sung Soo Oh, Ki Soo Park, Chan Joo Lee, Sungha Park, Seung-Koo Lee, Sang-Baek Koh, Sun Jae Jung, Changsoo Kim, Jaelim Cho\
Yonsei medical journal

## 2023

35. <span style="color:blue;">**Association between Low Hand Grip Strength and Decreased Femoral Neck Bone Mineral Density in Korean Fishery Workers**</span>\
Mi-Ji Kim, Gyeong-Ye Lee, Joo-Hyun SUNG, Seok-Jin HONG, Ki-Soo Park\
Journal of Agricultural Medicine & Community Health

36. **Associations of cold exposure with hospital admission and mortality due to acute kidney injury: a nationwide time-series study in Korea**\
Kyoung-Nam Kim, Moon-Kyung Shin, Youn-Hee Lim, Sanghyuk Bae, Jong-Hun Kim, Seung-Sik Hwang, Mi-Ji Kim, Jongmin Oh, Hyungryul Lim, Jonghyuk Choi, Ho-Jang Kwon\
Science of the Total Environment

37. **Change of femoral anteversion angle in children with intoeing gait measured by three-dimensional computed tomography reconstruction: 3-year follow-up study**\
Yeongchae Park, Hayoung Byun, Mi-Ji Kim, Heesuk Shin\
Annals of Rehabilitation Medicine

38. **한국 초고령 노인에서 폭염한파와 오존이 사망에 미치는 단기적 영향**\
신문경, 김경남, 배상혁, 김미지, 김종헌, 권호장, 황승식, 김효은, 안윤진\
Public Health Weekly Report

39. **Heavy metal exposure linked to metabolic syndrome in Korean male firefighters: FRESH cohort cross-sectional analysis**\
Jee Eun Choi, Mun-Joo Bae, Mi-Ji Kim, Sung Soo Oh, Ki Soo Park, Chan Joo Lee, Sungha Park, Sang-Baek Koh, Jaelim Cho, Changsoo Kim\
Scientific reports

## 2022

25. **Nutrition and Psychosocial Factors were associated with Possible Sarcopenia in the Rural Elderly**\
Bokyoung Kim, Gyeong-Ye Lee, Ae-Rim Seo, Mi-Ji Kim, Sung-Hyo Seo, Ki-Soo Park\
Journal of Agricultural Medicine and Community Health

26. **The effect of polycyclic aromatic hydrocarbons on changes in the brain structure of firefighters: An analysis using data from the Firefighters Research on Enhancement of Safety & Health study**\
Yun Tae Kim, Woojin Kim, Mun-joo Bae, Jee Eun Choi, Mi-Ji Kim, Sung Soo Oh, Ki Soo Park, Sungha Park, Seung-Koo Lee, Sang-Baek Koh, Changsoo Kim\
Science of the Total Environment

27. **Clinical and histopathological analyses of kidney biopsies in a single center for 7 years**\
Seunghye Lee, Sehyun Jung, Mi-Ji Kim, Jong Sil Lee, Ha Nee Jang, Se-Ho Chang, Hyun-Jung Kim\
Medicine

28. **Association between disability and edema index values in rural older adult osteosarcopenia patients**\
Soo-Hyun Park, Mi-Ji Kim, Bokyoung Kim, Gyeong-Ye Lee, Young-Mi Seo, Jin-Young Park, Ae-Rim Seo, Sung-Hyo Seo, Ki-Soo Park\
Yonsei Medical Journal

29. **Population attributable fraction of indicators for musculoskeletal diseases: a cross-sectional study of fishers in Korea**\
Jaehoo Lee, Bohyun Sim, Bonggyun Ju, Chul Gab Lee, Ki-Soo Park, Mi-Ji Kim, Jeong Ho Kim, Kunhyung Kim, Hansoo Song\
Annals of occupational and environmental medicine

30. **Associations between cold spells and hospital admission and mortality due to diabetes: A nationwide multi-region time-series study in Korea**\
Kyoung-Nam Kim, Youn-Hee Lim, Sanghyuk Bae, Jong-Hun Kim, Seung-Sik Hwang, Mi-Ji Kim, Jongmin Oh, Hyungryul Lim, Jonghyuk Choi, Ho-Jang Kwon\
Science of The Total Environment

31. **Automatic plaque removal using dual-energy computed tomography angiography: Diagnostic accuracy and utility in patients with peripheral artery disease**\
Byeong-Ju Koo, Jung-Ho Won, Ho-Cheol Choi, Jae-Boem Na, Ji-Eun Kim, Mi-Jung Park, Sa-Hong Jo, Hyun-Oh Park, Chung-Eun Lee, Mi-Ji Kim, Sung-Eun Park\
Medicina

32. **남해군에서의 소지역 건강 격차 해소 사업**\
강양화, 박수정, 서애림, 김미지, 김보경, 박기수\
Public Health Weekly Report

33. <span style="color:blue;">**Effect of high temperature on walking among residents of rural and urban communities**</span>\
Mi-Ji Kim, Joo Hyun Sung, Ki-Soo Park\
Yonsei Medical Journal

34. **Percutaneous nephrostomy for complex renal stones: percutaneous renal access behind the stone versus renal calyx dilation**\
Jae Kyeong Ahn, Jung Ho Won, Dae Seob Choi, Ho Cheol Choi, Hye Young Choi, Sa Hong Jo, Jae Hwi Choi, Seung Hye Lee, Mi Ji Kim, Sung Eun Park, Ji Hoon Shin\
Plos one

## 2021

22. **Translation and validation of the Korean version of the Sarcopenia Quality of Life (SarQoL-K®) questionnaire and applicability with the SARC-F screening tool**\
Jun-Il Yoo, Yong-Chan Ha, Miji Kim, Sung-Hyo Seo, Mi-Ji Kim, Gyeong-Ye Lee, Young-Mi Seo, Changsu Sung, Ki-Soo Park\
Quality of Life Research

23. **Associations between frailty in older adults and malnutrition in rural areas: 2019 updated version of the Asian working group for sarcopenia**\
Ae-Rim Seo, Mi-Ji Kim, Bokyoung Kim, Young-Mi Seo, Gyeong-Ye Lee, Ki-Soo Park, Jun-Il Yoo\
Yonsei Medical Journal

24. **Muscle exercise mitigates the negative influence of low socioeconomic status on the lack of muscle strength: A Cross-Sectional study**\
Hanna Lee, Mi-Ji Kim, Junhee Lee, Mingyo Kim, Young Sun Suh, Hyun-Ok Kim, Yun-Hong Cheon\
Healthcare

## 2020

15. **Cohort Profile: Firefighter Research on the Enhancement of Safety and Health (FRESH), a Prospective Cohort Study on Korean Firefighters**\
Yun Tae Kim, Woo Jin Kim, Jee Eun Choi, Mun Joo Bae, Heeseon Jang, Chan Joo Lee, Hye-Jeong Lee, Dong Jin Im, Byoung Seok Ye, Mi-Ji Kim, Yeoju Jeong, Sung Soo Oh, Young-Chul Jung, Eun Seok Kang, Sungha Park, Seung Koo Lee, Ki Soo Park, Sang Baek Koh, Changsoo Kim\
Yonsei medical journal

16. **Barriers related to walking activity according to the age group of rural residents**\
Bokyoung Kim, Gyeong-Ye Lee, Ae-Rim Seo, Mi-Ji Kim, Sung-Hyo Seo, Ki-Soo Park\
Journal of agricultural medicine & community health

17. **Validation of the Western Ontario and McMaster Universities arthritis index short form (WOMAC-SF) and its relevance to disability and frailty**\
Soo-Hyun Park, Byeong-Hun Kang, Mi-Ji Kim, Bokyoung Kim, Gyeong-Ye Lee, Young-Mi Seo, Jun-Il Yoo, Ki-Soo Park\
Yonsei Medical Journal

18. <span style="color:blue;">**Association of the Western Ontario and McMaster Universities Osteoarthritis Index (WOMAC) with muscle strength in community-dwelling elderly with knee osteoarthritis**</span>\
Mi-Ji Kim, Byeong-Hun Kang, Soo-Hyun Park, Bokyoung Kim, Gyeong-Ye Lee, Young-Mi Seo, Ki-Soo Park, Jun-Il Yoo\
International journal of environmental research and public health

19. **Blood pressure and the risk of major adverse cardiovascular events among firefighters**\
Juhwan Noh, Chan Joo Lee, Dae-Sung Hyun, Woojin Kim, Mi-Ji Kim, Ki-Soo Park, Sangbaek Koh, Sei-Jin Chang, Changsoo Kim, Sungha Park\
Journal of hypertension

20. **Comparison of lamina cribrosa morphology in normal tension glaucoma and autosomal-dominant optic atrophy**\
Gyu-Nam Kim, Ji-Ah Kim, Mi-Ji Kim, Eun Ji Lee, Jeong-Min Hwang, Tae-Woo Kim\
Investigative Ophthalmology & Visual Science

21. **Regional Differences in the Association between Dietary Patterns and Muscle Strength in Korean Older Adults: Data from the Korea National Health and Nutrition Examination Survey 2014–2016**\
Ae-Rim Seo, Mi-Ji Kim, Ki-Soo Park\
Nutrients

## 2019

9. <span style="color:blue;">**The association of the exposure to work-related traumatic events and work limitations among firefighters: A cross-sectional study**</span>\
Mi-Ji Kim, Yeoju Jeong, Yeun-Soon Choi, Ae-Rim Seo, Yeongmi Ha, Minjeong Seo, Ki-Soo Park\
International Journal of Environmental Research and Public Health

10. **The association between frailty and disability among the elderly in rural areas of Korea**\
Yeun-Soon Choi, Mi-Ji Kim, Gyeong-Ye Lee, Young-Mi Seo, Ae-Rim Seo, Bokyoung Kim, Jun-Il Yoo, Ki Soo Park\
International journal of environmental research and public health

11. **Prevalence of upper extremity musculoskeletal diseases and disability among fruit tree farmers in Korea: cross-sectional study**\
Minju Kim, Jun-Il Yoo, Mi-Ji Kim, Jae-Boem Na, Sang-Il Lee, Ki-Soo Park\
Yonsei medical journal

12. <span style="color:blue;">**The association of perceived neighborhood walkability and environmental pollution with frailty among community-dwelling older adults in Korean rural areas: A cross-sectional study**</span>
Mi-Ji Kim, Sung-Hyo Seo, Ae-Rim Seo, Bo-Kyoung Kim, Gyeong-Ye Lee, Yeun-Soon Choi, Jin-Hwan Kim, Jang-Rak Kim, Yune-Sik Kang, Baek-Geun Jeong, Ki-Soo Park\
Journal of Preventive Medicine and Public Health

13. **Effect of burnout on post-traumatic stress disorder symptoms among firefighters in Korea: Data from the Firefighter Research on Enhancement of Safety & Health (FRESH)**\
Woojin Kim, Munjoo Bae, Sei-Jin Chang, Jin-Ha Yoon, Da Yee Jeong, Dae-Sung Hyun, Hye-Yoon Ryu, Ki-Soo Park, Mi-Ji Kim, Changsoo Kim\
Journal of preventive medicine and public health

14. **Association between air conditioning use and self-reported symptoms during the 2018 heat wave in Korea**\
Yong-Han Lee, Sanghyuk Bae, Seung-sik Hwang, Jong-Hun Kim, Kyoung-Nam Kim, Youn-Hee Lim, Miji Kim, Sohwa Jung, Ho-Jang Kwon\
Journal of preventive medicine and public health

## 2018

4. **Relationships among medication adherence, lifestyle modification, and health-related quality of life in patients with acute myocardial infarction: a cross-sectional study**\
Yu-Mi Lee, Rock Bum Kim, Hey Jean Lee, Keonyeop Kim, Min-Ho Shin, Hyeung-Keun Park, Soon-Ki Ahn, So Young Kim, Young-Hoon Lee, Byoung-Gwon Kim, Heeyoung Lee, Won Kyung Lee, Kun Sei Lee, Mi-Ji Kim, Ki-Soo Park\
Health and quality of life outcomes

5. **Common upper extremity disorders and function affect upper extremity-related quality of life: A community-based sample from rural areas**\
Dong Kyu Moon, Young Jin Park, Sang-Youn Song, Mi Ji Kim, Jin Sung Park, Dae-Cheol Nam, Dong-Hee Kim, Jae-Boem Na, Sang-Il Lee, Sun Chul Hwang, Ki-Soo Park\
Yonsei medical journal

6. **WHO disability assessment schedule 2.0 is related to upper and lower extremity disease-specific quality of life**\
Jun-Il Yoo, Jin-Sung Park, Rock-Beum Kim, Ae-Rim Seo, Young-Jin Park, Mi-Ji Kim, Ki Soo Park\
Quality of Life Research

7. <span style="color:blue;">**Determining functional activity profiles in patients with upper extremity disorders: is there effect modification by hand-grip strength?**</span>\
Mi-Ji Kim, Ki Soo Park, Ae-Rim Seo, Sang-Il Lee, Yong-Chan Ha, Jun-Il Yoo\
Clinical interventions in aging

8. **Relationship between endothelial function and skeletal muscle strength in community dwelling elderly women**\
Jun‐Il Yoo, Mi‐Ji Kim, Jae‐Bum Na, Yun‐Hong Chun, Young‐Jin Park, Yongwhi Park, Young‐Sool Hah, Yong‐Chan Ha, Ki Soo Park\
Journal of Cachexia, Sarcopenia and Muscle

## 2017

2. **Impact of health-related quality of life in firefighters: focused on posttraumatic stress, health-related work limitations, and family support**\
Park Ki-Soo, Ha Yeongmi, Seo Minjeong, Choi Yeun-Soon, Kim Mi-Ji, Jeong Yeoju, Yang Seungkyoung\
Korean journal of occupational health nursing

3. **Effects of Depressive Symptom and Health Status on Several Factors that Affect Suicidal Ideation among the Elderly Living Alone in Rural Area -The Fully Mediating Effect of Depressive Symptom-**\
Yeunsoon Choi, Miji Kim, Ae Rim Seo, Hyun Ok Kim, Ki Soo Park\
Korean Journal of Health Promotion

## 2013

1. **Histone H3 lysine 27 and 9 hypermethylation within the Bad promoter region mediates 5-Aza-2′-deoxycytidine-induced Leydig cell apoptosis: implications of 5-Aza-2′-deoxycytidine toxicity to male reproduction**\
Ji-Young Choi, Sangmi Lee, Soojin Hwang, Sangmee Ahn Jo, Miji Kim, Young Ju Kim, Myung-Geol Pang, Inho Jo\
Apoptosis

---
